// Generated by CoffeeScript 1.6.3
(function ($) {
    var calculatePrice, openMailForm, replaceAll, resetFeature, selectFeature, to_num, to_s, toggleInputs;
    to_s = function (nStr) {
        var rgx, x, x1, x2;
        nStr += "";
        x = nStr.split(".");
        x1 = x[0];
        x2 = (x.length > 1 ? "." + x[1] : "");
        rgx = /(\d+)(\d{3})/;
        while (rgx.test(x1)) {
            x1 = x1.replace(rgx, "$1" + "," + "$2");
        }
        return x1 + x2;
    };
    to_num = function (string) {
        return parseFloat(replaceAll(',', '', string));
    };
    replaceAll = function (find, replace, str) {
        return str.replace(new RegExp(find, 'g'), replace);
    };
    calculatePrice = function (price, active) {
        var $lastPrice, currentPrice;
        $lastPrice = $('#last-price .value');
        currentPrice = to_num($lastPrice.text());
        if (active) {
            currentPrice -= to_num(price);
        } else {
            currentPrice += to_num(price);
        }
        return $lastPrice.text(to_s(currentPrice));
    };
    selectFeature = function () {
        var active, args, duration, price;
        duration = $('input[name=contract-duration]:checked').val();
        console.log(duration);
        if (duration === '6') {
            if ($(this).find('.feature-price').length) {
                price = $(this).find('.feature-price span').text();
            } else {
                price = '0';
            }
            if ($(this).hasClass('active')) {
                active = true;
            } else {
                active = false;
            }
            calculatePrice(price, active);
            return $(this).toggleClass('active');
        } else {
            args = {
                'padding': [30, 25, 30, 25],
                'closeBtn': false
            };
            return $.fancybox('Vui lòng chọn hợp đồng 6 tháng để tuỳ chọn tiện nghi.', args);
        }
    };
    resetFeature = function () {
        $('#room-feature-no-include #features li').each(function (i, el) {
            return $(this).removeClass('active');
        });
        return $('#last-price .value').text($('#rental-price').text());
    };
    toggleInputs = function () {
        if ($(this).val() === 'between' || $(this).val() === 'not between') {
            $(this).parent().find('.value').hide();
            $(this).parent().find('.min').show();
            return $(this).parent().find('.max').show();
        } else {
            $(this).parent().find('.min').hide();
            $(this).parent().find('.max').hide();
            return $(this).parent().find('.value').show();
        }
    };
    openMailForm = function () {
        var $btnSend, $message;
        $btnSend = $('#btn-send-invoice').detach();
        $message = $('#form-send-invoice').find('#content');
        $message.text($('#invoice-print').html());
        $.fancybox($('#send-invoice-wrapper').html());
        return $('#invoice-print').append($btnSend);
    };
    return $(document).ready(function ($) {
        if ($('.node-type-room').length) {
            $('#room-feature-no-include #features').on('click', 'li', selectFeature);
            $('input[name=contract-duration]').on('change', resetFeature);
            $('#contract-duration').buttonset();
        }
        //if ($('.view-rooms, .view-house-room-list').length) {
        //    $('.views-field-field-images').live('hover', function () {
        //        return $(this).find('.description').toggleClass('display');
        //    });
        //}
        //if ($('.view-id-search_room.view-display-id-page').length) {
        //    $('.views-field-field-images').live('hover', function () {
        //        return $(this).find('.description').toggleClass('display');
        //    });
        //}
        if ($('#block-phongdep-room-search').length) {
            $('#area_op').on('change', toggleInputs);
            $('#price_op').on('change', toggleInputs);
        }
        if ($('.node-type-invoice').length) {
            return $('#btn-send-invoice').on('click', openMailForm);
        }

    });
})(jQuery);