//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Entities;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Dal
{

    public partial class MimosaEntities : DbContext
    {
        public MimosaEntities()
            : base("name=MimosaEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<BookingRoomEquipment> BookingRoomEquipments { get; set; }
        public DbSet<BookingRoomService> BookingRoomServices { get; set; }
        public DbSet<BookingStatus> BookingStatus { get; set; }
        public DbSet<Component> Components { get; set; }
        public DbSet<ContactInformation> ContactInformations { get; set; }
        public DbSet<ContactType> ContactTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ImageType> ImageTypes { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<LocaleStringResource> LocaleStringResources { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<RoleComponentPermission> RoleComponentPermissions { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomEquipment> RoomEquipments { get; set; }
        public DbSet<RoomService> RoomServices { get; set; }
        public DbSet<RoomStatus> RoomStatus { get; set; }
        public DbSet<RoomType> RoomTypes { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SiteGroup> SiteGroups { get; set; }
        public DbSet<SiteGroupSite> SiteGroupSites { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TagVersion> TagVersions { get; set; }
        public DbSet<UserRoleAuth> UserRoleAuths { get; set; }
        public DbSet<UtilityDay> UtilityDays { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<VisitorOfDay> VisitorOfDays { get; set; }

    }
}