//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.RoomEquipments = new HashSet<RoomEquipment>();
        }
    
        public int EquipmentId { get; set; }
        public int OrganisationId { get; set; }
        public string EquipmentName { get; set; }
        public bool IsLegacy { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RealPrice { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<RoomEquipment> RoomEquipments { get; set; }
    }
}
