//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public int ImageTypeId { get; set; }
        public int ItemId { get; set; }
        public string FileName { get; set; }
        public byte[] ImageContent { get; set; }
        public byte[] ImageSmallContent { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string Description { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ImageType ImageType { get; set; }
    }
}
