//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Equipments = new HashSet<Equipment>();
            this.RoomTypes = new HashSet<RoomType>();
            this.Services = new HashSet<Service>();
            this.Sites = new HashSet<Site>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int OrganisationID { get; set; }
        public string Name { get; set; }
        public int ContactInformationID { get; set; }
        public int DisplayIndex { get; set; }
        public bool IsLegacy { get; set; }
        public string AuthorisationCode { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ContactInformation ContactInformation { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<RoomType> RoomTypes { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
