//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleComponentPermission
    {
        public int RoleComponentPermissionId { get; set; }
        public System.Guid RoleId { get; set; }
        public int ComponentId { get; set; }
        public Nullable<bool> WriteRight { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual Component Component { get; set; }
    }
}
