//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomEquipment
    {
        public RoomEquipment()
        {
            this.BookingRoomEquipments = new HashSet<BookingRoomEquipment>();
        }
    
        public int RoomEquipmentId { get; set; }
        public int RoomId { get; set; }
        public int EquipmentId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<BookingRoomEquipment> BookingRoomEquipments { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Room Room { get; set; }
    }
}
