//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Rooms = new HashSet<Room>();
            this.RoomTypes = new HashSet<RoomType>();
            this.SiteGroupSites = new HashSet<SiteGroupSite>();
            this.UserRoleAuths = new HashSet<UserRoleAuth>();
        }
    
        public int SiteID { get; set; }
        public int OrganisationID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string Name { get; set; }
        public string AbbreviatedName { get; set; }
        public Nullable<int> ContactInformationID { get; set; }
        public Nullable<System.Guid> LicenseKey { get; set; }
        public Nullable<decimal> StarRating { get; set; }
        public string PropCode { get; set; }
        public int DisplayIndex { get; set; }
        public bool IsLegacy { get; set; }
        public int Availability { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ContactInformation ContactInformation { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<RoomType> RoomTypes { get; set; }
        public virtual ICollection<SiteGroupSite> SiteGroupSites { get; set; }
        public virtual ICollection<UserRoleAuth> UserRoleAuths { get; set; }
    }
}
