//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteGroup
    {
        public SiteGroup()
        {
            this.SiteGroupSites = new HashSet<SiteGroupSite>();
            this.UserRoleAuths = new HashSet<UserRoleAuth>();
        }
    
        public int SiteGroupId { get; set; }
        public string GroupName { get; set; }
        public byte[] Concurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<SiteGroupSite> SiteGroupSites { get; set; }
        public virtual ICollection<UserRoleAuth> UserRoleAuths { get; set; }
    }
}
