//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagVersion
    {
        public int TagVersionID { get; set; }
        public string TagName { get; set; }
        public string Version { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
