//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityDay
    {
        public System.DateTime DateEntry { get; set; }
        public Nullable<System.DateTime> DateWeekStarting { get; set; }
        public Nullable<System.DateTime> DateWeekEnding { get; set; }
        public Nullable<System.DateTime> DateMonthStarting { get; set; }
        public Nullable<System.DateTime> DateMonthEnding { get; set; }
        public Nullable<System.DateTime> DateYear1 { get; set; }
        public Nullable<System.DateTime> DateYear2 { get; set; }
        public Nullable<System.DateTime> DateYear3 { get; set; }
        public Nullable<System.DateTime> DateYear4 { get; set; }
        public Nullable<System.DateTime> DateYear5 { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateYear1Offset { get; set; }
        public Nullable<System.DateTime> DateYear2Offset { get; set; }
        public Nullable<System.DateTime> DateYear3Offset { get; set; }
        public Nullable<System.DateTime> DateYear4Offset { get; set; }
        public Nullable<System.DateTime> DateYear5Offset { get; set; }
    }
}
